version: "3"

services:
  web:
    command: python3 ./manage.py runserver 0.0.0.0:8000
    image: project-name:local
    ports:
      - 8000:8000
    volumes:
      - ../backend:/backend
      - build:/build
    links:
      - webpack
      - ssr

  ssr:
    image: project-name-webpack:local
    command: npm run ssr
    ports:
      - 3001:3001
    environment:
      EXPRESS_PORT: 3001
    volumes:
      - ../frontend/package.json:/frontend/package.json
      - build:/build

  webpack:
    image: project-name-webpack:local
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ../frontend/src:/frontend/src
      - ../frontend/webpack.config.js:/frontend/webpack.config.js
      - ../frontend/babel.config.js:/frontend/babel.config.js
      - ../frontend/package.json:/frontend/package.json
      - ../frontend/node_modules:/frontend/node_modules
      - build:/build

volumes:
  build:
